[pytest]
pythonpath =
    .
    restapi
testpaths =
    tests
    restapi/tests
norecursedirs =
    external_resources
    .git
    .venv
    .pytest_tmp*
    restapi/outputs
    outputs
addopts = --import-mode=importlib -p no:cacheprovider --basetemp=.pytest_tmp
